#!/opt/perl-5.30/bin/perl

use v5.30;
use warnings;

my $deploy = '';
{
    print "local or deploy? ";
    chomp(my $ans = <STDIN>);
    redo if $ans !~ /^(local|deploy)\z/;
    $deploy = '--deployment' if $ans eq 'deploy';
}

system("/opt/perl-5.30/bin/carton install $deploy");
