# mojolicious
requires 'Mojolicious';
#   mojo optional dependencies
requires 'Cpanel::JSON::XS';
requires 'EV';
requires 'IO::Socket::Socks';
requires 'IO::Socket::SSL';
requires 'Net::DNS::Native';
#requires 'Plack';
#requires 'Role::Tiny';

# misc
requires 'experimentals';
requires 'List::AllUtils';

# db
requires 'DBIx::Class';
requires 'DBIx::Class::Helpers';
requires 'DBIx::Class::Schema::Loader';
requires 'DBD::Pg';

# dev
requires 'Data::Printer';

# MetaCPAN API
requires 'MetaCPAN::Client';
requires 'JSON::Validator';
requires 'DateTime::Format::RFC3339';
requires 'DateTime::Format::ISO8601';
